# Generated by Django 6.0.5 on 2026-05-23 02:19

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='專案名稱')),
                ('description', models.TextField(blank=True, verbose_name='專案說明')),
                ('network_segment', models.CharField(blank=True, max_length=100, verbose_name='網段（如 192.168.1.0/24）')),
                ('status', models.CharField(choices=[('active', '進行中'), ('archived', '已封存'), ('deleted', '已刪除')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '專案',
                'verbose_name_plural': '專案',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PacketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.pcap_upload_path, verbose_name='PCAP 檔案')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='檔案大小 (bytes)')),
                ('capture_time', models.DateTimeField(blank=True, null=True, verbose_name='擷取時間')),
                ('description', models.TextField(blank=True, verbose_name='檔案備註')),
                ('network_tag', models.CharField(blank=True, max_length=100, verbose_name='網段標籤')),
                ('status', models.CharField(choices=[('pending', '等待處理'), ('processing', '處理中'), ('done', '已完成'), ('failed', '處理失敗')], default='pending', max_length=20)),
                ('packet_count', models.IntegerField(default=0, verbose_name='封包數量')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 校驗碼')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_files', to='projects.project', verbose_name='所屬專案')),
            ],
            options={
                'verbose_name': '封包檔案',
                'verbose_name_plural': '封包檔案',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '擁有者'), ('editor', '編輯者'), ('viewer', '檢視者')], default='editor', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '專案成員',
                'verbose_name_plural': '專案成員',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_projects', through='projects.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
