# Generated by Django 6.0.5 on 2026-05-23 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登入系統'), ('logout', '登出系統'), ('upload_pcap', '上傳 PCAP'), ('run_analysis', '執行分析'), ('run_gradcam', '執行 Grad-CAM'), ('export_report', '匯出報告'), ('create_project', '建立專案'), ('delete_session', '刪除 Session')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日誌',
                'verbose_name_plural': '操作日誌',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '系統管理員'), ('analyst', '資安分析師'), ('viewer', '唯讀檢視者')], default='analyst', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='所屬組織')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='頭像')),
                ('bio', models.TextField(blank=True, verbose_name='個人簡介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_upload_pcap', models.BooleanField(default=True, verbose_name='可上傳 PCAP')),
                ('can_run_ai_analysis', models.BooleanField(default=True, verbose_name='可執行 AI 分析')),
                ('can_export_report', models.BooleanField(default=True, verbose_name='可匯出報告')),
                ('can_manage_projects', models.BooleanField(default=True, verbose_name='可管理專案')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者資料',
                'verbose_name_plural': '使用者資料',
            },
        ),
    ]
