# Generated by Django 4.2.29 on 2026-08-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', '登入系統'), ('logout', '登出系統'), ('upload_pcap', '上傳 PCAP'), ('run_analysis', '執行分析'), ('run_gradcam', '執行 Grad-CAM'), ('export_report', '匯出報告'), ('create_project', '建立專案'), ('delete_session', '刪除 Session'), ('ai_chat', 'AI 對話')], max_length=30),
        ),
    ]
