# Generated by Django 6.0.5 on 2026-05-23 02:19

import analyzer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pcap', 'PCAP 離線分析'), ('live', '即時擷取')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('pcap_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('task_status', models.CharField(choices=[('pending', '等待中'), ('running', '分析中'), ('done', '已完成'), ('failed', '分析失敗')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='Celery Task ID')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('packet_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('packet_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='projects.packetfile', verbose_name='來源封包檔')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='projects.project', verbose_name='所屬專案')),
            ],
            options={
                'verbose_name': '分析 Session',
                'verbose_name_plural': '分析 Session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF 報告'), ('json', 'JSON 資料'), ('csv', 'CSV 告警清單')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=analyzer.models.report_upload_path)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.analysissession')),
            ],
            options={
                'verbose_name': '分析報告',
                'verbose_name_plural': '分析報告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('src_ip', models.CharField(max_length=50)),
                ('dst_ip', models.CharField(blank=True, max_length=50)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analyzer.analysissession')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CNNResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('normal_count', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('avg_normal_error', models.FloatField(default=0)),
                ('avg_attack_error', models.FloatField(default=0)),
                ('detection_rate', models.FloatField(default=0, verbose_name='偵測率')),
                ('error_histogram', models.ImageField(blank=True, null=True, upload_to='cnn_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cnn_result', to='analyzer.analysissession')),
            ],
            options={
                'verbose_name': 'CNN 結果',
                'verbose_name_plural': 'CNN 結果',
            },
        ),
        migrations.CreateModel(
            name='GradCAMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_index', models.IntegerField(verbose_name='封包索引')),
                ('variant', models.CharField(choices=[('gradcam', 'Grad-CAM'), ('gradcam++', 'Grad-CAM++'), ('scorecam', 'Score-CAM')], default='gradcam', max_length=20)),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='是否為異常封包')),
                ('recon_error', models.FloatField(default=0, verbose_name='重建誤差')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=analyzer.models.gradcam_upload_path, verbose_name='原始影像')),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to=analyzer.models.gradcam_upload_path, verbose_name='熱力圖')),
                ('comparison_image', models.ImageField(blank=True, null=True, upload_to=analyzer.models.gradcam_upload_path, verbose_name='對比圖')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradcam_images', to='analyzer.analysissession')),
            ],
            options={
                'verbose_name': 'Grad-CAM 影像',
                'verbose_name_plural': 'Grad-CAM 影像',
                'ordering': ['session', 'packet_index'],
                'unique_together': {('session', 'packet_index', 'variant')},
            },
        ),
    ]
