# Generated by Django 5.2.12 on 2026-08-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysissession_model_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnnresult',
            name='known_attack_count',
            field=models.IntegerField(default=0, verbose_name='已知攻擊數（分類器判定）'),
        ),
        migrations.AddField(
            model_name='cnnresult',
            name='unknown_attack_count',
            field=models.IntegerField(default=0, verbose_name='未知/新型攻擊數（VAE 重建誤差判定）'),
        ),
    ]
